# バージョンの指定
version: 2.1

# マシーンのイメージを指定します
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
# ここで実行したいコマンドをrunの後ろにつづけて記述していきます。今回であれば"echo Hello, World!"とゆうコマンドを入力することです。nameは特に意味はありません。
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
# 最後に実行手順の記述をします。今回は一つしかないので順番はありませんが上から順に実行されていきます。基本的には処理の早いものから記述していきます
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
# 他にも追加で記述できることはたくさんあります公式ドキュメント’https://circleci.com/docs/ja/’を参照ください